Mcts upper bound expected value logit processor
fynnkroeger/llm-inference-time-scaling pull request #2
Opened 2024-11-20 14:17 UTC by ko-redtruck

2024-11-20 16:52 UTC, Lietze requested changes
Ich find doof, dass es nicht einheitlich mit dem inference script ist. Wird falls man das später einheitlich haben will refactored werden müssen, aber speed over quality oder so.
Utils und runner sollte nicht im rl Ordner sein.
runner vielleicht auch besser benennen. Das macht eigentlich Evaluation der samples oder? Vielleicht "evaluate_samples.py" oder so.

2024-11-20 16:52 UTC, Lietze commented on rl/runner.py
> +    results to f"{sample_file}_results.jsonl.gz"
Change and write some acctual documentation. It returns the solved problems from the given samples right?

2024-11-20 16:52 UTC, Lietze commented on rl/runner.py
> +    k: List[int] = [1, 10, 100],
I don't think k is used

2024-12-03 10:45 UTC, ko-redtruck commented
Parse output functionality:

- Split function into lines with assert
- Parse assert with ast
- Evaluate assert input args and output args with extended ast.literal_eval function

Parsing fails for complex scenarios such as a for loop over different assert statements. In this case it defaults to the normal evaluation

2024-12-04 16:24 UTC, merged